### ISSUE TITLE
I'm not able to finish my Game in time

### ISSUE THREAD

**Issue by Grubchri** [rstropek-teaching/real-time-game-quiz-4bhif-Grubchri#1]
Dear Mr. Stropek, as the title says, I want to apologize that i will not be able to complete my game until tomorrow, because of bad time handling and 'problems' with the amount of homeworks i had to do over the christmas holidays, I hope you will understand my concerns and allow me to finish it until next week. ( sunday at latest),

**Comment by rstropek** [comment]
Thank you for letting me know. Try to work on the project until next week. It will be a great exercise for the exam.

Greetings,
Rainer Stropek.
