### ISSUE TITLE
Not able to push my solution

### ISSUE THREAD

**Issue by Grubchri** [rstropek-teaching/real-time-game-quiz-4bhif-Grubchri#2]
Dear Mr. Stropek,
I wanted to push my 'best solution' which i was possible to make in this time. But I couldn't due to an Git error "fatal: unable to access 'https://github.com/rstropek-teaching/real-time-game-quiz-4bhif-Grubchri.git/': The requested URL returned error: 403". So I will try to push it but I can not guarantee that I am able to. As a result to this I wanted to ask if it is okay for you, that I will show you in person what I was able to do in this time, although it doesn't meet all the requirements like being a multiplayer game with socketcommunication or that it somehow doesn't reload my changes made by the player.

**Comment by rstropek** [comment]
Hi @Grubchri 

Try the URL `https://github.com/rstropek-teaching/real-time-game-quiz-4bhif-Grubchri.git` (without the slash at the end). I think it should work. Please let me know if it doesn't.

Greetings,
Rainer Stropek.

**Comment by Grubchri** [comment]
Dear Mr. Stropek, 
I found out why I am not able to push, but I can't fix it. The problem: It recognizes a second user which shouldn't be in this repo and there is no directory above it which uses that user, I even tried to replace it locally with 'git config --local user.name "Grubchri" and it was written successfully in the config file. But it still throws the given error, which is that the user has no right to push. I even asked the system for my global username for git, but, it too, replies with the username "Grubchri", which is the correct username.
So is there still another way for me to fix this problem or do you have a glue what could stop hindering me from pushing?

**Comment by rstropek** [comment]
Probier doch mal den [GitHub Desktop](https://desktop.github.com/). Mit dem solltest du das Problem über eine GUI lösen können.

lg,
Rainer Stropek.

**Comment by Grubchri** [comment]
Vielen Dank für Ihr bemühen mir zu helfen, leider scheint es mir eher danach dass es mir in der Konsole nicht angezeigt wurde, dass schon mal gepushed wurde, weshalb auch immer, was dazu führte dass ich Ihre Zeit in Anspruch genommen habe obwohl anscheinend doch alles gepushed wurde.

**Comment by rstropek** [comment]
Kein Problem.
